au BufNewFile *.cpp -1r ~/template.cpp
au BufNewFile *.cpp normal G$=gg

nmap <F5> :w \| !g++ -std=c++17 -Wshadow -Wall %<CR>
nmap <F9> :w \| !g++ -std=c++17 -Wshadow -Wall % && ./a.out<CR>
nmap <F6> :w \| !g++ -std=c++17 -Wshadow -Wall % && ./a.out < in <CR>
nmap <F8> :w \| !cf test<CR>
nmap <F2> :w \| !g++ -std=c++17 -Wshadow -Wall % && ./a.out < in > out <CR>
nmap <F3> :w \| !./a.out <CR>

vnoremap <C-c> "+y
nmap <c-p> "+p
nmap <c-a> ggvG$


imap <c-_> <esc><leader>c<space>a
vmap <c-_> <leader>c<space>
nmap <c-_> <leader>c<space>

nmap <c-s> :w<CR>
imap <c-s> <Esc>:w<CR>a

imap <leader><TAB> <c-n>

"filetype detect
set nocompatible
set mouse=a
syntax on
filetype plugin on

set tabstop=4
set shiftwidth=4
"set expandtab
set smarttab
set autoindent
set smartindent

set showcmd
set number
"set autowrite
"set autoread

set shell=/usr/bin/zsh

" My Changes
set relativenumber

set path+=**
set wildmenu

set incsearch
set smartcase

set hidden

:filetype on
:autocmd FileType c,cpp :set cindent

" Status Line
set laststatus=2
set statusline=
set statusline+=%-3.3n\
set statusline+=%f\
set statusline+=%h%m%r%w
set statusline+=\[%{strlen(&ft)?&ft:'none'}]
set statusline+=%=
set statusline+=0x%-8B
set statusline+=%-14(%l,%c%V%)
set statusline+=%<%P

colorscheme apprentice

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
"let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<TAB>"
"let g:UltiSnipsJumpBackwardTrigger="<c-z>"

let g:UltiSnipsSnippetsDir = "~/.vim/UltiSnips"


"let g:loaded_matchparen=1

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_loc_list_height = 5
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_error_symbol = '❌'
let g:syntastic_style_error_symbol = '⁉️'
let g:syntastic_warning_symbol = '⚠️'
let g:syntastic_style_warning_symbol = '💩'

let g:syntastic_cpp_compiler_options = '-Wall -Wextra -pedantic -std=c++14 -O2 -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2 -fsanitize=address -fsanitize=undefined -fno-sanitize-recover -fstack-protector'

" clang complete options
"let g:clang_library_path='/usr/lib/llvm-4.0/lib'

"let g:clang_user_options='|| exit 0'


let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 1
let g:netrw_winsize = 25
let g:netrw_altv = 1

call plug#begin('~/.vim/plugged')

" For MS Windows, this is probably better:
"call plug#begin('~/vimfiles/plugged')

Plug 'SirVer/ultisnips'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'kaicataldo/material.vim'
Plug 'vim-syntastic/syntastic'
"Plug 'xavierd/clang_complete'
" ... etc

call plug#end()


